### ISSUE TITLE
PKIX path building failed: unable to find valid certification path to request to requested target

### ISSUE THREAD

**Issue by bharatbhushan1705** [apache/pulsar-helm-chart#492]
**Describe the bug**
The error message javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
**To Reproduce**
1. Use of self-signed certificate keystone
2. The TLS is enabled for proxy and broker
3. The Apache Pulsar is running in Openshift Cluster
4. The Apache Pulsar version 3.2.0

**Expected behavior**
When we are communicating directly to broker url it is working, we expect same when we try to connect via proxy.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
Error logs: 
2172
at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
2173
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
2174
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
2175
at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329) ~[?:?]
2176
... 17 more
2177
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2178
at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148) ~[?:?]
2179
at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129) ~[?:?]
2180
at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
2181
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
2182
at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
2183
at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
2184
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
2185
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
2186
at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329) ~[?:?]
2187
... 17 more

**Comment by nodece** [comment]
Could you share your yaml?

**Comment by lhotari** [comment]
Closing since there's no response from reporter. Please retest on latest released Pulsar Helm chart version.
