### ISSUE TITLE
upgrade to pulsar helm chart version 3.3.1 from 2.9.4->3.0.0->3.3.1 with the pulsar-broker error

### ISSUE THREAD

**Issue by jing-c-tyagi** [apache/pulsar-helm-chart#495]
[pulsar-broker-2-logs.txt](https://github.com/apache/pulsar-helm-chart/files/15211189/pulsar-broker-2-logs.txt)

**Describe the bug**
I 'm upgrading pulsar helm chart version 2.9.4 to 3.0.0 and to 3.3.1  and got the following error
pulsar-broker got CrashLoopBackOff status

**Screenshots**
![image](https://github.com/apache/pulsar-helm-chart/assets/135978735/4ab8efe8-3c79-4d38-9277-5586a4b05c20)

aws eks cluster AL2

**Additional context**
kubectl logs -n pulsar pulsar-broker-2 shows below logs.
2024-05-04T22:38:26,077+0000 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: java.io.IOException: Failed to bind to /0.0.0.0:80
org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to bind to /0.0.0.0:80
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:328) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:810) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:276) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:356) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:80
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:311) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	... 3 more
Caused by: java.net.BindException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:311) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	... 3 more
2024-05-04T22:38:26,087+0000 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to bind to /0.0.0.0:80
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:938) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:276) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:356) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
Caused by: org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to bind to /0.0.0.0:80
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:328) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:810) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	... 2 more
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:80
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:311) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:810) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	... 2 more
Caused by: java.net.BindException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[org.eclipse.jetty-jetty-server-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[org.eclipse.jetty-jetty-util-9.4.54.v20240208.jar:9.4.54.v20240208]
	at org.apache.pulsar.broker.web.WebService.start(WebService.java:311) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:810) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]
	... 2 more
2024-05-04T22:38:26,088+0000 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:55) ~[org.apache.pulsar-pulsar-common-3.0.3.jar:3.0.3]
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:50) ~[org.apache.pulsar-pulsar-common-3.0.3.jar:3.0.3]
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:82) ~[org.apache.pulsar-pulsar-common-3.0.3.jar:3.0.3]
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:359) ~[org.apache.pulsar-pulsar-broker-3.0.3.jar:3.0.3]

**Comment by lhotari** [comment]
You seem to have port 80 for the http port in the broker. That's not supported in the Helm chart since non

**Comment by jing-c-tyagi** [comment]
> You seem to have port 80 for the http port in the broker. That's not supported in the Helm chart since non-root containers are used. Port 80 can be used for the proxy.

Thanks, that's the exactly the problem.  my release values yaml file ./pulsar-2.10.2.yaml did have broker:ports:http: 80. After I change it to 8080 and run: helm upgrade --namespace pulsar pulsar  pulsar --values ./pulsar-2.10.2.yaml, the pulsar-broker pods are running up now. Thanks for your help!
